---
type: leaf

leaf:
  defaults:
    uplink_switches: [ BGP-SPINE1, BGP-SPINE2 ]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    filter:
      only_vlans_in_use: true
    inband_mgmt_subnet: 172.23.254.0/24
  nodes:
    - name: BGP-LEAF1
      id: 1
      uplink_switch_interfaces: [ Ethernet1, Ethernet1 ]
    - name: BGP-LEAF2
      id: 2
      uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]
