---
type: l3leaf
l3leaf:
  defaults:
    mlag_peer_ipv4_pool: 10.10.255.0/24
    mlag_peer_l3_ipv4_pool: 10.10.224.0/24
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 32
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    mlag_interfaces: [Ethernet5, Ethernet6]
  node_groups:
    - group: MLAG_PER_MTU_INTERFACE
      bgp_as: 923
      vtep: false
      nodes:
        - name: 7010TX-LEAF1
          id: 3
          platform: 7010TX
          mgmt_ip: 192.168.201.116/24
          vtep: true
        - name: 7010TX-LEAF2
          id: 4
          platform: 7010TX
          mgmt_ip: 192.168.201.117/24
