---
- name: Converge
  hosts: test_hosts
  gather_facts: false
  connection: local
  vars:
    tacacs_key_set_as_play_var: "071B245F5A"
    read_structured_config_from_file: False
  tasks:

    - name: Generate device intended config and documentation
      delegate_to: 127.0.0.1
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
