download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/arista-eos-10.0.1.tar.gz
format_version: 1.0.0
name: eos
namespace: arista
server: https://galaxy.ansible.com/api/
signatures: []
version: 10.0.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/arista/eos/versions/10.0.1/
